name: chakula_connect
description: A mobile app to connect surplus food donors with recipients.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # UI & Utilities
  cupertino_icons: ^1.0.8
  flutter_pw_validator: ^1.4.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.0
  flutter_image_compress: ^2.1.0
  intl_phone_field: ^3.1.0
  permission_handler: ^12.0.1
  provider: ^6.1.1
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_ringtone_player: ^4.0.0+4
  flutter_slidable: ^4.0.0
  firebase_storage: ^12.4.10



  # Maps & Location
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  location: ^8.0.1
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^3.0.1

  url_launcher: ^6.2.6

  # Animations & Effects
  animations: ^2.0.11
  lottie: ^3.1.2
  shimmer: ^3.0.0

  # Platform Support
  universal_io: ^2.2.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/chakula connect.png
    - assets/animations/
    - assets/icons/rider_bike.png  
    - assets/icons/home_marker.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoColorEmoji.ttf
